#
# Queries
#
type Query  {
   threatEvents_nationalCount(
        queryType:String!
        fieldStr:String
        threatType:String
        dateStart:DateRangeDuration
        dateEnd:DateRangeDuration
        limitVal:Int
    ):JSON

   threatEvents_nationalTopN(
        dimension:String!
        filterDimension:String
        filterVal:String
        dateStart:DateRangeDuration
        dateEnd:DateRangeDuration
        topN:Int
    ):JSON
}