type Query  {
   threatName(
      NameStr:String!
      topN:Int
         ): String
   threatSector(topN:Int): String
   threatClient(
      ClientName: String!
      ThreatType: String!
      ): String
}