#
# Queries
#
type Query {
  # Return threat details for a specific sector
  threatEvents_sectorDetails(
    dateStart: DateTime
    dateEnd: DateTime
    sector: String!
    filter: JSON
    having: JSON
    outgoing: Boolean = true
  ): JSON @authz
  # Custom API for SCAM demo
  threatEvents_sectorScamDetails(
    dateStart: DateTime
    dateEnd: DateTime
    sector: String!
    filter: JSON
    having: JSON
    outgoing: Boolean = true
  ): JSON @authz
  threatEvents_sectorScamCount(
    countryCode:String!
    dateStart:DateRangeDuration
    dateEnd:DateRangeDuration
    limitVal:Int
  ):JSON
  threatEvents_campaignScamCount(
      countryCode:String!
      dateStart:DateRangeDuration
      dateEnd:DateRangeDuration
      limitVal:Int
  ):JSON
  threatEvents_countryScamCount(
      countryCode:String!
      dateStart:DateRangeDuration
      dateEnd:DateRangeDuration
      limitVal:Int
  ):JSON
  threatEvents_countryScamN2N(
      countryCode:String!
      dateStart:DateRangeDuration
      dateEnd:DateRangeDuration
      limitVal:Int
  ):JSON
  threatEvents_sectorScamGraph(
      sectorName:String!
      dateStart:DateRangeDuration
      dateEnd:DateRangeDuration
      limitVal:Int
  ):JSON

}
