#
# Queries
#
type Query {
  # top N threat names with time series returns
  threatEvents_topNThreatNameCountTimeSeries(
    topN: Int! = 10 @valuelimit(max: 100)
    dateFrom: DateRangeDuration
    timeseries: TimeSeriesInput = {}
    # sectors: [Sector]
    filter: JSON
    having: JSON
  ): [TimeSeriesData2] @authz
  # top N friendly threat types with time series returns
  threatEvents_topNFriendlyThreatTypeCountTimeSeries(
    topN: Int! = 10 @valuelimit(max: 100)
    dateFrom: DateRangeDuration
    timeseries: TimeSeriesInput = {}
    sectors: [Sector]
  ): [TimeSeriesData2] @authz
  # top N threat names with time series returns
  threatEvents_threatCountTimeSeries(
    dateStart: DateTime
    dateEnd: DateTime
    filter: JSON
    having: JSON
  ): [TimeSeriesData2] @authz
}
